spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student-management?useSSL=false
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9003
